version: "3"
services:
  nacos-server:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-server
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone  # 使用独立模式，不依赖数据库

